# Generated by Django 2.0.1 on 2018-06-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='bag_helped',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='employees_type',
        ),
        migrations.AddField(
            model_name='employees',
            name='baghelped',
            field=models.IntegerField(choices=[(0, 'Bolsa Auxílio'), (1, 'Não'), (2, 'Sim')], default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='employeestype',
            field=models.IntegerField(choices=[(1, 'Colaborador(a)'), (2, 'Professor(a)')], default=0),
        ),
    ]
